---
apiVersion: v1
kind: Secret
metadata:
  name: {{ (.Values.global.activemq).secretname}}
type: Opaque
stringData:
  {{ (.Values.global.activemq).usersecretkey }}: {{ (.Values.global.activemq).username | quote }}
  {{ (.Values.global.activemq).pwdsecretkey }}: {{ (.Values.global.activemq).password | quote }}
  jetty-realm.properties: {{ printf "%s: %s, admin" (.Values.global.activemq).username (.Values.global.activemq).password | quote }}
