apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.global.platform.dbsecretname . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  database-username: {{ .Values.global.database.platform.username | quote }}
  database-password: {{ required "databaseSecrets.platformPassword must be set" .Values.databaseSecrets.platformPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.global.platform.worker.dbsecretname . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  worker-db-password: {{ required "databaseSecrets.workerPassword must be set" .Values.databaseSecrets.workerPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.postgres.secrets.postgres.name . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  postgres-password: {{ required "databaseSecrets.postgresPassword must be set" .Values.databaseSecrets.postgresPassword | quote }}
