apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-storage-secret
type: Opaque
stringData:
  accesskey: {{ .Values.global.storage.accesskey | quote }}
  secretkey: {{ .Values.global.storage.secretkey | quote }}
